platform :ios, '12.0'

ENV['SWIFT_VERSION'] = '5.0'

prepare_react_native_project!

linkage = flutter
pod 'Flutter', :path => 'Flutter'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target_ios_native_pods = use_native_modules!

  pod 'GeneratedPluginRegistrant', :path => 'Flutter'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
